apps/faq/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
from django.views.generic import ListView
from .models import Faq

__author__ = 'alexy'


urlpatterns = patterns(
    '',
    url(r'^$', ListView.as_view(model=Faq), name='list'),
)

cms/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import logout
import debug_toolbar
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', TemplateView.as_view(template_name='landing.html'), name='home'),
    url(r'^$', 'apps.landing.views.home_view', name='home'),
    url(r'^about/', include('apps.about.urls', namespace='about'),),
    url(r'^travels/', include('apps.travel.urls', namespace='travels'),),
    url(r'^groups/', include('apps.group.urls', namespace='groups'),),
    url(r'^excurse/', include('apps.excurse.urls', namespace='excurse'),),
    url(r'^ticket/', include('apps.ticket.urls', namespace='ticket'),),
    url(r'^faq/', include('apps.faq.urls', namespace='faq'),),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('core.urls')),
    url(r'^accounts/logout/$', logout, name='logout'),
    url(r'^inplaceeditform/', include('inplaceeditform.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

templates/__includes/footer.html
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <ul class="footer-ul">
          <li class="footer-ul-li">
            <span class="footer-copyright">&copy; 2015, все права защищены</span>
          </li>
          <li class="footer-ul-li">
            <a href="{% url 'home' %}" class="footer-link">Главная</a>
          </li>
          {% include '__includes/nav.html' %}
          <li class="footer-ul-li">
            e-mail: <a href="mailto:manager@enjoy-sa.ru" class="footer-link">manager@enjoy-sa.ru</a>
          </li>
        </ul>
    </div>
  </div>
</footer>

templates/__includes/nav.html
<li><a href="{% url 'about:list' %}" class="icon-about"><img src="{{ STATIC_URL }}img/menu/icon-about.png" alt="О нас">О нас</a></li>
<li><a href="{% url 'travels:list' %}" class="icon-travel"><img src="{{ STATIC_URL }}img/menu/icon-travel.png" alt="Журнал путешествий">Журнал путешествий</a></li>
<li><a href="{% url 'groups:list' %}" class="icon-group"><img src="{{ STATIC_URL }}img/menu/icon-group.png" alt="Наши туры">Наши туры</a></li>
<li><a href="{% url 'excurse:list' %}" class="icon-excurse"><img src="{{ STATIC_URL }}img/menu/icon-excurse.png" alt="Экскурсии">Экскурсии</a></li>
<li><a href="{% url 'faq:list' %}" class="icon-faq"><img src="{{ STATIC_URL }}img/menu/icon-faq.png" alt="Вопросы и ответы">Вопросы и ответы</a></li>

templates/__includes/pagination.html
{#<div class="col-lg-12">#}
{#  <div class="text-center">#}
{#    <ul class="pagination">#}
{#      <li>#}
{#        <a href="#" aria-label="Previous">#}
{#          <span aria-hidden="true">&laquo;</span>#}
{#        </a>#}
{#      </li>#}
{#      <li><a href="#">1</a></li>#}
{#      <li><a href="#">2</a></li>#}
{#      <li><a href="#">3</a></li>#}
{#      <li><a href="#">4</a></li>#}
{#      <li><a href="#">5</a></li>#}
{#      <li>#}
{#        <a href="#" aria-label="Next">#}
{#          <span aria-hidden="true">&raquo;</span>#}
{#        </a>#}
{#      </li>#}
{#    </ul>#}
{#  </div>#}
{#</div>#}