apps/group/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView
from apps.group.views import GroupDetailView, GroupListView
from .models import Group

__author__ = 'alexy'


urlpatterns = patterns(
    '',
    url(r'^$', GroupListView.as_view(), name='list'),
    url(r'^comment/$', 'apps.group.views.comment', name='comment'),
    url(r'^(?P<slug>[\w-]+)$', GroupDetailView.as_view(), name='detail'),
)

cms/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import logout
import debug_toolbar
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', TemplateView.as_view(template_name='landing.html'), name='home'),
    url(r'^$', 'apps.landing.views.home_view', name='home'),
    url(r'^about/', include('apps.about.urls', namespace='about'),),
    url(r'^travels/', include('apps.travel.urls', namespace='travels'),),
    url(r'^groups/', include('apps.group.urls', namespace='groups'),),
    url(r'^excurse/', include('apps.excurse.urls', namespace='excurse'),),
    url(r'^ticket/', include('apps.ticket.urls', namespace='ticket'),),
    url(r'^faq/', include('apps.faq.urls', namespace='faq'),),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('core.urls')),
    url(r'^accounts/logout/$', logout, name='logout'),
    url(r'^inplaceeditform/', include('inplaceeditform.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/group/models.py
# coding=utf-8
import os
import uuid
from ckeditor.fields import RichTextField
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from imagekit.models import ImageSpecField
from pilkit.processors import SmartResize
from pytils.translit import slugify
from core.base_model import Common, CommonPage, Comment

__author__ = 'alexy'


def get_image_path(self, filename):
    extension = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), extension)
    return os.path.join('group', filename)


def get_banner_path(self, filename):
    extension = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), extension)
    return os.path.join('banner', filename)


class GroupSection(models.Model):
    class Meta:
        verbose_name = u'Направление'
        verbose_name_plural = u'Направления'
        app_label = 'group'

    def __unicode__(self):
        return self.name

    name = models.CharField(verbose_name=u'Название', max_length=250)


class Group(CommonPage):
    class Meta:
        verbose_name = u'Наш тур'
        verbose_name_plural = u'Наши туры'
        app_label = 'group'
        ordering = ['-created', ]

    def __unicode__(self):
        if self.travel_start and self.travel_end:
            return u'Тур - %s, с %s по %s' % (self.title, self.travel_start, self.travel_end)
        else:
            return u'Тур - %s' % self.title

    def save(self):
        # self.slug = slugify(self.title)
        if self.travel_start and self.travel_end:
            delta = self.travel_end - self.travel_start
            self.day_count = delta.days
        super(Group, self).save()

    def get_absolute_url(self):
        return reverse('groups:detail', kwargs={'slug': self.slug})

    def pic(self):
        return '<img src="%s" width="170"/>' % self.cover_resize.url

    GROUP_TYPE_CHOICES = (
        (0, u'Присоединиться к туру'),
        (1, u'Пример тура'),
    )

    pic.short_description = u"Обложка"
    pic.allow_tags = True

    type = models.PositiveSmallIntegerField(verbose_name=u'Тип тура', choices=GROUP_TYPE_CHOICES, default=0)
    groupsection = models.ManyToManyField(to=GroupSection, verbose_name=u'Направление', blank=True, null=True)
    description = RichTextField(verbose_name=u'Описание', blank=True, null=True)
    reserved = models.PositiveIntegerField(verbose_name=u'Забронировано мест', default=0)
    seats = models.PositiveIntegerField(verbose_name=u'Количество мест', default=0)
    price = models.PositiveIntegerField(verbose_name=u'Стоимость', default=0)
    cover = models.ImageField(verbose_name=u'Обложка', upload_to=get_image_path)
    cover_resize = ImageSpecField(
        [SmartResize(*settings.GROUP_COVER_SIZE)], source='cover', format='JPEG', options={'quality': 94}
    )
    travel_start = models.DateField(verbose_name=u'Прибытие', blank=True, null=True)
    travel_end = models.DateField(verbose_name=u'Отъезд', blank=True, null=True)
    slug = models.SlugField(max_length=100, verbose_name=u'url')
    day_count = models.PositiveIntegerField(default=0, verbose_name=u'Количество дней')


class GroupComment(Comment):
    class Meta:
        verbose_name = u'Комментарий'
        verbose_name_plural = u'Комментарии'
        app_label = 'group'

    group = models.ForeignKey(to=Group, verbose_name=u'Тур')


class GroupBanner(models.Model):
    class Meta:
        verbose_name = u'Баннер'
        verbose_name_plural = u'Баннеры'
        app_label = 'group'

    def __unicode__(self):
        return self.name

    name = models.CharField(verbose_name=u'Название', max_length=256)
    image = models.ImageField(verbose_name=u'Обложка', upload_to=get_banner_path)

apps/group/forms.py
# coding=utf-8
from django.forms import ModelForm, HiddenInput, TextInput, Textarea
from .models import GroupComment

__author__ = 'alexy'


class GroupCommentForm(ModelForm):
    class Meta:
        model = GroupComment
        exclude = []
        widgets = {
            'user': HiddenInput(),
            'group': HiddenInput(),
            'text': Textarea(attrs={'class': 'form-control'}),
        }

apps/group/views.py
# coding=utf-8
from annoying.decorators import ajax_request
from django.db.models import Max, Min
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, ListView
from .forms import GroupCommentForm
from .models import Group, GroupSection, GroupBanner

__author__ = 'alexy'


class GroupListView(ListView):
    model = Group

    def get_queryset(self):
        qs = Group.objects.all()
        if self.request.GET.get('type'):
            type = int(self.request.GET.get('type'))
            queryset = qs.filter(type=type)
        elif self.request.GET.get('section'):
            es_pk = int(self.request.GET.get('section'))
            queryset = qs.filter(groupsection__pk=es_pk)
        elif self.request.GET.get('min') and self.request.GET.get('max'):
            min_price = int(self.request.GET.get('min'))
            max_price = int(self.request.GET.get('max'))
            queryset = qs.filter(price__gte=min_price).filter(price__lte=max_price)
        elif self.request.GET.get('dmin') and self.request.GET.get('dmax'):
            min_days = int(self.request.GET.get('dmin'))
            max_days = int(self.request.GET.get('dmax'))
            queryset = qs.filter(day_count__gte=min_days).filter(day_count__lte=max_days)
        else:
            queryset = qs
            # print(qs.aggregate(Max('price')))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(GroupListView, self).get_context_data(**kwargs)
        qs = Group.objects.all()
        context.update(
            qs.aggregate(Min('price'))
        )
        context.update(
            qs.aggregate(Max('price'))
        )
        context.update(
            qs.aggregate(Max('day_count'))
        )
        context.update(
            qs.aggregate(Min('day_count'))
        )
        context.update({
            'group_section_list': GroupSection.objects.all()
        })
        if GroupBanner.objects.all().count() != 0:
            context.update({
                'group_banner_list': GroupBanner.objects.all()
            })
        return context


class GroupDetailView(DetailView):
    model = Group

    def get_context_data(self, **kwargs):
        context = super(GroupDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            comment_form = GroupCommentForm(
                initial={
                    'group': self.object,
                    'user': self.request.user
                }
            )
            context.update({
                'comment_form': comment_form
            })
        return context


@ajax_request
def comment(request):
    if request.method == 'POST':
        form = GroupCommentForm(request.POST)
        print form
        if form.is_valid():
            new_comment = form.save()
            new_comment.save()
            return {
                'success': u'Ваш комментарий сохранён'
            }
        else:
            return {
                'success': u'Текст комментария не может быть пустым'
            }
    else:
        return HttpResponseRedirect('/groups/')

apps/group/templates/group/group_comment.html
<div class="row bg-info">
  <div class="comment">
    <div class="col-lg-12">
      <p class="lead">Комментарии:</p>
      <hr>
    {% if object.groupcomment_set.all %}
      {% for comment in object.groupcomment_set.all %}
        <div class="comment-item">
          <div class="comment-item-avatar">
            <img src="{{ comment.user.avatar_resize.url }}" alt="{{ comment.user.get_full_name }}">
          </div>
          <div class="comment-item-content">
            <div class="comment-item-content-name">
              <span>{{ comment.user.get_full_name }} </span>
              <span class="glyphicon glyphicon-calendar"></span>
              <span class="small">{{ comment.created }}</span>
            </div>
            <div class="comment-item-content-text">
              {{ comment.text|safe|default:'' }}
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif %}
    {% if comment_form %}
      <form action="{% url 'groups:comment' %}" method="post" class="comment-form js-comment-form" role="form">{% csrf_token %}
      {{ comment_form.as_p }}
      <button type="submit" class="btn btn-success">Отправить</button>
    </form>
    {% else %}
    <p class="comment__text">
    Только <a href="#js-modal-auth" id="js-auth-button">зарегистрированные</a> пользователи могут оставлять комментарии
    </p>
    {% endif %}
    </div>
    <div class="clearfix"></div>
  </div>
</div>

apps/group/templates/group/group_detail.html
{% extends 'index.html' %}
{% block content %}
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="page__title">
            <h1>{{ object.title|default:'' }}</h1>
          </div>
          <div class="page-desc">
            <div class="col-lg-8 col-lg-offset-2">
              <table class="table">
                <tr>
                  <th>Прибытие:</th>
                  <th>Отъезд:</th>
                  <th>Забронировано мест:</th>
                  <th>Количество мест:</th>
                  <th>Стоимость:</th>
                </tr>
                <tr>
                  <td>{{ object.travel_start|default:''}}</td>
                  <td>{{ object.travel_end|default:''}}</td>
                  <td>{{ object.reserved|default:''}}</td>
                  <td>{{ object.seats|default:''}}</td>
                  <td>{{ object.price|default:''}}$</td>
                </tr>
              </table>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="page-cover">
            <img src="{{ object.cover.url }}" alt="{{ object.name|default:'' }}" class="page-cover__img">
          </div>
          <div class="page__content">
            {{ object.description|safe }}
          </div>
          <div class="page__button">
            <a href="#js-modal-ticket" class="btn btn-success btn-lg js-ticket-button" data-group="{{ object.id }}">Присоединиться к группе</a>
          </div>

        </div>
      </div>
      {% include 'group/group_comment.html' %}
    </div>
  </div>
{% endblock %}

apps/group/templates/group/group_list.html
{% extends 'base.html' %}
{% block content %}
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
        {% if group_banner_list %}
          {% for item in group_banner_list %}
          <div class="groups-banner">
            <img src="{{ item.image.url }}" alt="{{ item.name|default:'' }}" class="groups-banner__image">
          </div>
          {% endfor %}
        {% else %}
          <div class="page__title">
            <h1>{{ page.title|default:'Наши туры' }}</h1>
          </div>
          {% if page.text %}
          <div class="page__text">
            {{ page.text|safe|default:'' }}
          </div>
          {% endif %}
        {% endif %}
        </div>
        <div class="col-lg-12">
          <div class="groups-type">
            <ul class="groups-type-list">
              <li class="groups-type-list-item"><a href="{% url 'groups:list' %}" class="btn btn-warning">Все туры</a></li>
              <li class="groups-type-list-item"><a href="?type=1" class="btn btn-info">Примеры туров<span
                  class="small">  (по запросу)</span></a></li>
              <li class="groups-type-list-item"><a href="?type=0" class="btn btn-info">Присоединиться к туру</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-2">
        {% if object_list %}
          <p class="bold">Направления:</p>
          {% if group_section_list %}
          <ul class="groups-section-list">
            <li class="groups-section-list-item"><a href="{% url 'groups:list' %}" class="groups-section-list-item__link">Все направления</a></li>
            {% for section in group_section_list %}
            <li><a href="?section={{ section.id }}" class="groups-section-list-item__link">{{ section.name|default:'' }}</a></li>
            {% endfor %}
          </ul>
          {% endif %}
          <p>
            <label for="amount">Диапазон цен:</label>
            <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
          </p>
          <div id="slider-range"></div>
          {% if day_count__max != 0 %}
          <p>
            <label for="days">Количество дней:</label>
            <input type="text" id="days" readonly style="border:0; color:#f6931f; font-weight:bold;">
          </p>
          <div id="slider-range-days"></div>
          {% endif %}
          <a href="{% url 'groups:list' %}" class="js-amount-button btn btn-success ammount-button" data-min-price="{{ price__min }}"
             data-max-price="{{ price__max }}" data-min-days="{{ day_count__min }}"
             data-max-days="{{ day_count__max }}" >Найти</a>
        {% endif %}
        </div>
        <div class="col-lg-10">
          <div class="groups">
          {% if object_list %}
            {% for object in object_list %}
            <div class="col-lg-12">
              <div class="groups-item">
                <div class="groups-item-cover">
                  <img src="{{ object.cover_resize.url }}" class="groups-item-cover__img" alt="{{ object.title|default:'' }}">
                </div>
                <div class="groups-item-content">
                  <a href="{{ object.get_absolute_url }}" class="groups-item-content__link">
                    <h2 class="groups-item-content__title">
                      {{ object.title|default:'' }}
                    </h2>
                  </a>
                  <table class="table">
                    {% if object.type == 0 %}
                    <tr>
                      <td>
                        <span class="glyphicon glyphicon-plane"></span>
                        <span class="table_text">Прибытие:</span>
                        <b>{{ object.travel_start|default:'' }}</b>
                      </td>
                      <td>
                        <span class="table_text">Забронировано мест:</span>
                        <b>{{ object.reserved|default:'' }}</b>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <span class="glyphicon glyphicon-calendar"></span>
                        <span class="table_text">Отъезд:</span>
                        <b>{{ object.travel_end|default:'' }}</b>
                      </td>
                      <td>
                        <span class="table_text">Количество мест:</span>
                        <b>{{ object.seats|default:'' }}</b>
                      </td>
                    </tr>
                    {% else %}
                    <tr>
                      <td colspan="2">
                        <span class="glyphicon glyphicon-calendar"></span>
                        <span class="table_text">Длительност тура (дней):</span>
                        <b>{{ object.day_count|default:'' }}</b>
                      </td>
                    </tr>
                    <tr>
                      <td colspan="2">
                        <span class="glyphicon glyphicon-usd"></span>
                        <span class="table_text">
                          Стоимость тура: от <b>{{ object.price|default:'' }}$</b>
                        </span>
                      </td>
                    </tr>
                    {% endif %}
                    <tr>
                      <td class="text-center" colspan="2">
                        {% if object.type == 0 %}{% if object.price %}Стоимость тура: <b>{{ object.price|default:'' }}$</b>{% endif %}{% endif %}
                        <a href="#js-modal-ticket" class="btn btn-warning js-ticket-button" data-group="{{ object.id }}">
                        {% if object.type == 0 %}
                          Присоединиться к группе!
                        {% else %}
                          Узнать подробности
                        {% endif %}
                        </a>
                      </td>
                    </tr>
                  </table>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
            {% endfor %}
          {% endif %}
            <div class="clearfix"></div>
          </div>
        </div>
        {% include '__includes/pagination.html' %}
      </div>
    </div>
  </div>
{% endblock %}