apps/excurse/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
from django.views.generic import TemplateView, ListView, DetailView
from .views import ExcurseListView, ExcurseDetailView
from .models import Excurse

__author__ = 'alexy'


urlpatterns = patterns(
    '',
    url(r'^$', ExcurseListView.as_view(), name='list'),
    url(r'^comment/$', 'apps.excurse.views.comment', name='comment'),
    url(r'^(?P<slug>[\w-]+)$', ExcurseDetailView.as_view(), name='detail'),
    # url(r'^', ListView.as_view(template_name='excurse/excurse_list.html'), name='list'),
)

cms/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import logout
import debug_toolbar
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', TemplateView.as_view(template_name='landing.html'), name='home'),
    url(r'^$', 'apps.landing.views.home_view', name='home'),
    url(r'^about/', include('apps.about.urls', namespace='about'),),
    url(r'^travels/', include('apps.travel.urls', namespace='travels'),),
    url(r'^groups/', include('apps.group.urls', namespace='groups'),),
    url(r'^excurse/', include('apps.excurse.urls', namespace='excurse'),),
    url(r'^ticket/', include('apps.ticket.urls', namespace='ticket'),),
    url(r'^faq/', include('apps.faq.urls', namespace='faq'),),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('core.urls')),
    url(r'^accounts/logout/$', logout, name='logout'),
    url(r'^inplaceeditform/', include('inplaceeditform.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/excurse/models.py
# coding=utf-8
import os
import uuid
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from ckeditor.fields import RichTextField
from imagekit.models import ImageSpecField
from pilkit.processors import SmartResize
from pytils.translit import slugify
from core.base_model import CommonPage, Comment

__author__ = 'alexy'

def get_image_path(self, filename):
    extension = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), extension)
    return os.path.join('excurse', filename)


class ExcurseSection(models.Model):
    class Meta:
        verbose_name = u'Направление'
        verbose_name_plural = u'Направления'
        app_label = 'excurse'

    def __unicode__(self):
        return self.name

    name = models.CharField(verbose_name=u'Название', max_length=250)


class Excurse(CommonPage):
    class Meta:
        verbose_name = u'Экскурсия'
        verbose_name_plural = u'Экскурсии'
        app_label = 'excurse'
        ordering = ['-created', ]

    def __unicode__(self):
        return self.title

    # def save(self):
    #     self.slug = slugify(self.title)
    #     super(Excurse, self).save()

    def pic(self):
        return '<img src="%s" width="170"/>' % self.cover_resize.url

    def get_absolute_url(self):
        return reverse('excurse:detail', kwargs={'slug': self.slug})

    pic.short_description = u"Обложка"
    pic.allow_tags = True

    section = models.ForeignKey(to=ExcurseSection, verbose_name=u'Направление')
    # name = models.CharField(verbose_name=u'Название', max_length=250)
    cover = models.ImageField(upload_to=get_image_path, verbose_name=u'Обложка')
    cover_resize = ImageSpecField(
        [SmartResize(*settings.EXCURSE_COVER_SIZE)], source='cover', format='JPEG', options={'quality': 94}
    )
    price = models.PositiveIntegerField(verbose_name=u'Стоимость', blank=True, null=True)
    price_desc = models.TextField(verbose_name=u'Описание стоимости', blank=True, null=True)
    time = models.CharField(verbose_name=u'Длительность', max_length=250, blank=True, null=True)
    start = models.CharField(verbose_name=u'Отправка', max_length=250, blank=True, null=True)
    text = RichTextField(verbose_name=u'Текст')
    slug = models.SlugField(max_length=100, verbose_name=u'url')


class ExcursePhoto(models.Model):
    class Meta:
        verbose_name = u'Фотография с экскурсии'
        verbose_name_plural = u'Фотографии с экскурсии'
        app_label = 'excurse'

    def __unicode__(self):
        return self.name

    def pic(self):
        return '<img src="%s" width="170"/>' % self.image_resize.url

    pic.short_description = u"Обложка"
    pic.allow_tags = True

    excurse = models.ForeignKey(to=Excurse, verbose_name=u'Экскурсия')
    name = models.CharField(verbose_name=u'Название', max_length=250)
    image = models.ImageField(upload_to=get_image_path, verbose_name=u'Фотография')
    image_resize = ImageSpecField(
        [SmartResize(*settings.EXCURSE_COVER_SIZE)], source='image', format='JPEG', options={'quality': 94}
    )


class ExcurseComment(Comment):
    class Meta:
        verbose_name = u'Комментарий'
        verbose_name_plural = u'Комментарии'
        app_label = 'excurse'

    excurse = models.ForeignKey(to=Excurse, verbose_name=u'Экскурсия')

apps/excurse/forms.py
# coding=utf-8
from django.forms import ModelForm, HiddenInput, TextInput, Textarea
from .models import ExcurseComment

__author__ = 'alexy'

class ExcurseCommentForm(ModelForm):
    class Meta:
        model = ExcurseComment
        exclude = []
        widgets = {
            'user': HiddenInput(),
            'excurse': HiddenInput(),
            'text': Textarea(attrs={'class': 'form-control'}),
        }

apps/excurse/views.py
# coding=utf-8
from annoying.decorators import ajax_request
from django.db.models import Min
from django.db.models import Max
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView
from apps.excurse.forms import ExcurseCommentForm
from .models import Excurse, ExcurseSection

__author__ = 'alexy'


class ExcurseListView(ListView):
    model = Excurse

    def get_queryset(self):
        qs = Excurse.objects.all()
        if self.request.GET.get('section'):
            es_pk = int(self.request.GET.get('section'))
            queryset = qs.filter(section__pk=es_pk)
        elif self.request.GET.get('min') and self.request.GET.get('max'):
            min_price = int(self.request.GET.get('min'))
            max_price = int(self.request.GET.get('max'))
            queryset = qs.filter(price__gte=min_price).filter(price__lte=max_price)
        else:
            queryset = qs
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ExcurseListView, self).get_context_data(**kwargs)
        qs = Excurse.objects.all()
        context.update(
            qs.aggregate(Min('price'))
        )
        context.update(
            qs.aggregate(Max('price'))
        )
        context.update({
            'excurse_section_list': ExcurseSection.objects.all()
        })
        return context


class ExcurseDetailView(DetailView):
    model = Excurse

    def get_context_data(self, **kwargs):
        context = super(ExcurseDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            comment_form = ExcurseCommentForm(
                initial={
                    'excurse': self.object,
                    'user': self.request.user
                }
            )
            context.update({
                'comment_form': comment_form
            })
        return context


@ajax_request
def comment(request):
    if request.method == 'POST':
        form = ExcurseCommentForm(request.POST)
        print form
        if form.is_valid():
            new_comment = form.save()
            new_comment.save()
            return {
                'success': u'Ваш комментарий сохранён'
            }
        else:
            return {
                'success': u'Текст комментария не может быть пустым'
            }
    else:
        return HttpResponseRedirect('/excurse/')

apps/excurse/templates/excurse/excurse_comment.html
<div class="row bg-info">
  <div class="comment">
    <div class="col-lg-12">
      <p class="lead">Комментарии:</p>
      <hr>
    {% if object.excursecomment_set.all %}
      {% for comment in object.excursecomment_set.all %}
        <div class="comment-item">
          <div class="comment-item-avatar">
            <img src="{{ comment.user.avatar_resize.url }}" alt="{{ comment.user.get_full_name }}">
          </div>
          <div class="comment-item-content">
            <div class="comment-item-content-name">
              <span>{{ comment.user.get_full_name }} </span>
              <span class="glyphicon glyphicon-calendar"></span>
              <span class="small">{{ comment.created }}</span>
            </div>
            <div class="comment-item-content-text">
              {{ comment.text|safe|default:'' }}
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif %}
    {% if comment_form %}
      <form action="{% url 'excurse:comment' %}" method="post" class="comment-form js-comment-form" role="form">{% csrf_token %}
      {{ comment_form.as_p }}
      <button type="submit" class="btn btn-success">Отправить</button>
    </form>
    {% else %}
    <p class="comment__text">
    Только <a href="#js-modal-auth" id="js-auth-button">зарегистрированные</a> пользователи могут оставлять комментарии
    </p>
    {% endif %}
    </div>
    <div class="clearfix"></div>
  </div>
</div>

apps/excurse/templates/excurse/excurse_detail.html
{% extends 'index.html' %}
{#{% block title %}{% if object.meta_title %}{{ object.meta_title|default:'Сафари по ЮАР' }}{% else %}{{ object.title|default:'' }}{% endif %}{% endblock %}#}
{#{% block meta_desc %}{{ object.meta_desc|default:'' }}{% endblock %}">#}
{#{% block meta_key %}{{ object.meta_key|default:'' }}{% endblock %}">#}
{% block content %}
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="page__title">
            <h1>{{ object.title|default:'' }}</h1>
          </div>
          {% if object.price or object.time or object.start %}
          <div class="page-desc">
            <div class="col-lg-8 col-lg-offset-2">
              <table class="table">
                <tr>
                  <th>Длительность:</th>
                  <th>Отправка</th>
                  <th>Стоимость</th>
                </tr>
                <tr>
                  <td>{{ object.time|default:' '}}ч.</td>
                  <td>{{ object.start|default:' '}}</td>
                  <td>{% if object.price %}от {{ object.price|default:' '}}${% endif %}{% if object.price_desc %} {{ object.price_desc|default:'' }}{% endif %}</td>
                </tr>
              </table>
            </div>
            <div class="clearfix"></div>
          </div>
          {% endif %}
          <div class="page-cover">
            <img src="{{ object.cover.url }}" alt="{{ object.name|default:'' }}" class="page-cover__img">
          </div>
          <div class="page__content">
            {{ object.text|safe }}
          </div>
          <div class="page__button">
            <a href="#js-modal-ticket" class="btn btn-success btn-lg js-ticket-button" data-excurse="{{ object.id }}">Заказать экскурсию</a>
          </div>

        </div>
      </div>
      {% if object.excursephoto_set.all %}
      <div class="row">
        <div class="page-gallery">
        {% for photo in object.excursephoto_set.all %}
          <div class="col-lg-4">
            <div class="page-gallery-item">
              <a href="{{ photo.image.url }}" rel="photo-group" class="page-gallery__link js-page-gallery" title="{{ photo.name }}">
                <img src="{{ photo.image_resize.url }}" class="page-gallery__photo" alt="{{ photo.name }}">
              </a>
            </div>
          </div>
          {% endfor %}
          <div class="clearfix"></div>
        </div>
      </div>
      {% endif %}
      {% include 'excurse/excurse_comment.html' %}
    </div>
  </div>
{% endblock %}

apps/excurse/templates/excurse/excurse_list.html
{% extends 'base.html' %}
{% block content %}
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="page__title">
            <h1>{{ page.title|default:'Экскурсии' }}</h1>
          </div>
          {% if page.text %}
          <div class="page__text">
            {{ page.text|safe|default:'' }}
          </div>
          {% endif %}
        </div>
        <div class="excurse">
        {% if excurse_section_list %}
          <div class="col-lg-12">
            <ul class="excurse-section-list">
              <li class="excurse-section-list-item"><a href="{% url 'excurse:list' %}" class="excurse-section-list-item__link btn btn-warning">Все
                направления</a></li>
            {% for section in excurse_section_list %}
              <li class="excurse-section-list-item"><a href="?section={{ section.id }}"  class="excurse-section-list__link btn btn-info">{{ section.name|default:'' }}</a></li>
            {% endfor %}
            </ul>
            {% if price__min and price__max %}
            <p class="text-center">
              <label for="amount">Диапазон цен:</label>
              <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
            </p>
            <div id="slider-range"></div>
            <div class="text-center">
              <a href="{% url 'excurse:list' %}" class="js-amount-button btn btn-success ammount-button" data-min-price="{{ price__min }}"
                data-max-price="{{ price__max }}" >Подобрать по цене</a>
            </div>
            {% endif %}
          </div>
          <div class="clearfix"></div>
        {% endif %}
          {% for object in object_list %}
          <div class="col-lg-4 col-xs-12">
            <div class="excurse-item">
              <a href="{{ object.get_absolute_url }}" class="excurse-item__link">
                <div class="excurse-item-cover">
                  <img src="{{ object.cover_resize.url }}" alt="{{ object.title }}" class="excurse-item-cover__img">
                </div>
                <h2 class="excurse-item__title">{{ object.title|default:'' }}</h2>
                <div class="excurse-item-desc">
                  <p class="excurse-item-desc__text">
                    {{ object.text|striptags|truncatechars:150 }}
                  </p>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
          <div class="clearfix"></div>
        </div>
        {% include '__includes/pagination.html' %}
      </div>
    </div>
  </div>
{% endblock %}