apps/travel/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
from .views import TravelCreateView, TravelListView, TravelDetailView

__author__ = 'alexy'

urlpatterns = patterns(
    '',
    url(r'^$', TravelListView.as_view(), name='list'),
    url(r'^add/$', TravelCreateView.as_view(), name='add'),
    url(r'^comment/$', 'apps.travel.views.comment', name='comment'),
    url(r'^(?P<slug>[\w-]+)$', TravelDetailView.as_view(), name='detail'),
)

cms/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import logout
import debug_toolbar
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', TemplateView.as_view(template_name='landing.html'), name='home'),
    url(r'^$', 'apps.landing.views.home_view', name='home'),
    url(r'^about/', include('apps.about.urls', namespace='about'),),
    url(r'^travels/', include('apps.travel.urls', namespace='travels'),),
    url(r'^groups/', include('apps.group.urls', namespace='groups'),),
    url(r'^excurse/', include('apps.excurse.urls', namespace='excurse'),),
    url(r'^ticket/', include('apps.ticket.urls', namespace='ticket'),),
    url(r'^faq/', include('apps.faq.urls', namespace='faq'),),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('core.urls')),
    url(r'^accounts/logout/$', logout, name='logout'),
    url(r'^inplaceeditform/', include('inplaceeditform.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/travel/models.py
# -*- coding: utf-8 -*-
import os
import uuid
from ckeditor.fields import RichTextField
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from imagekit.models import ImageSpecField
from pilkit.processors import SmartResize
from pytils.translit import slugify
from core.base_model import Common, CommonPage, Comment
from core.models import User

__author__ = 'alexy'


def get_image_path(self, filename):
    extension = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), extension)
    return os.path.join('travel', filename)


class Travel(CommonPage):
    class Meta:
        verbose_name = u'Статья'
        verbose_name_plural = u'Статьи'
        app_label = 'travel'

    def __unicode__(self):
        return self.title
    #
    # def save(self):
    #     if not self.slug:
    #         self.slug = slugify(self.title)
    #     super(Travel, self).save()

    def get_absolute_url(self):
        return reverse('travels:detail', kwargs={'slug': self.slug})

    def pic(self):
        return '<img src="%s" width="170"/>' % self.cover_resize.url

    pic.short_description = u"Обложка"
    pic.allow_tags = True

    user = models.ForeignKey(to=User, verbose_name=u'Пользователь')
    # title = models.CharField(verbose_name=u'Заголовок', max_length=255)
    text = RichTextField(verbose_name=u'Текст')
    cover = models.ImageField(verbose_name=u'Обложка', upload_to=get_image_path)
    cover_resize = ImageSpecField(
        [SmartResize(*settings.TRAVEL_COVER_SIZE)], source='cover', format='JPEG', options={'quality': 94}
    )
    slug = models.SlugField(max_length=100, verbose_name=u'url')


class TravelComment(Comment):
    class Meta:
        verbose_name = u'Комментарий'
        verbose_name_plural = u'Комментарии'
        app_label = 'travel'

    travel = models.ForeignKey(to=Travel, verbose_name=u'Статья')

apps/travel/forms.py
# coding=utf-8
from django.forms import ModelForm, HiddenInput, TextInput, Textarea
from .models import Travel, TravelComment

__author__ = 'alexy'


class TravelCreateForm(ModelForm):
    class Meta:
        model = Travel
        # fields = ('user', 'travel_review', 'text')
        exclude = []
        widgets = {
            'user': HiddenInput(),
            'slug': HiddenInput(),
            'title': TextInput(attrs={'class': 'form-control'}),
            'text': TextInput(attrs={'class': 'form-control'}),
        }


class TravelCommentForm(ModelForm):
    class Meta:
        model = TravelComment
        exclude = []
        widgets = {
            'user': HiddenInput(),
            'travel': HiddenInput(),
            'text': Textarea(attrs={'class': 'form-control'}),
        }

apps/travel/views.py
# coding=utf-8
from annoying.decorators import ajax_request
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from core.models import User
from .models import Travel
from .forms import TravelCreateForm, TravelCommentForm

__author__ = 'alexy'


class TravelCreateView(CreateView):
    model = Travel
    form_class = TravelCreateForm

    def get_initial(self):
        username = self.request.user
        return {
            'user': username,
        }


class TravelListView(ListView):
    model = Travel

    def get_queryset(self):
        qs = Travel.objects.all()
        if self.request.GET.get('author'):
            author_pk = int(self.request.GET.get('author'))
            queryset = qs.filter(user__pk=author_pk)
        else:
            queryset = qs
        return queryset

    def get_context_data(self, **kwargs):
        context = super(TravelListView, self).get_context_data(**kwargs)
        context.update({
            'author_list': User.objects.filter(first_name__isnull=False, last_name__isnull=False).exclude(avatar='')
        })
        return context


class TravelDetailView(DetailView):
    model = Travel

    def get_context_data(self, **kwargs):
        context = super(TravelDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            comment_form = TravelCommentForm(
                initial={
                    'travel': self.object,
                    'user': self.request.user
                }
            )
            context.update({
                'comment_form': comment_form
            })
        return context

@ajax_request
def comment(request):
    if request.method == 'POST':
        form = TravelCommentForm(request.POST)
        print form
        if form.is_valid():
            new_comment = form.save()
            new_comment.save()
            return {
                'success': u'Ваш комментарий сохранён'
            }
        else:
            return {
                'success': u'Текст комментария не может быть пустым'
            }
    else:
        return HttpResponseRedirect('/travels/')

apps/travel/templates/travel/travel_comment.html
<div class="row bg-info">
  <div class="comment">
    <div class="col-lg-12">
      <p class="lead">Комментарии:</p>
      <hr>
    {% if object.groupcomment_set.all %}
      {% for comment in object.groupcomment_set.all %}
        <div class="comment-item">
          <div class="comment-item-avatar">
            <img src="{{ comment.user.avatar_resize.url }}" alt="{{ comment.user.get_full_name }}">
          </div>
          <div class="comment-item-content">
            <div class="comment-item-content-name">
              <span>{{ comment.user.get_full_name }} </span>
              <span class="glyphicon glyphicon-calendar"></span>
              <span class="small">{{ comment.created }}</span>
            </div>
            <div class="comment-item-content-text">
              {{ comment.text|safe|default:'' }}
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif %}
    {% if comment_form %}
      <form action="{% url 'travels:comment' %}" method="post" class="comment-form js-comment-form" role="form">{% csrf_token %}
      {{ comment_form.as_p }}
      <button type="submit" class="btn btn-success">Отправить</button>
    </form>
    {% else %}
    <p class="comment__text">
    Только <a href="#js-modal-auth" id="js-auth-button">зарегистрированные</a> пользователи могут оставлять комментарии
    </p>
    {% endif %}
    </div>
    <div class="clearfix"></div>
  </div>
</div>

apps/travel/templates/travel/travel_detail.html
{% extends 'index.html' %}
{% block top_js %}
{% endblock %}
{% block content %}
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="page__title">
            <h1>{{ object.title|default:'' }}</h1>
          </div>
          <div class="page-cover">
            <img src="{{ object.cover.url }}" alt="{{ object.name|default:'' }}" class="page-cover__img">
          </div>
          <div class="page__content">
            {{ object.text|safe }}
          </div>
        </div>
      </div>
      {% include 'travel/travel_comment.html' %}
    </div>
  </div>
{% endblock %}

apps/travel/templates/travel/travel_form.html
{% extends 'base.html' %}
{% block top_js %}
  {{ form.media }}
{% endblock %}
{% block content %}
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="page__title">
            <h1>Создание статьи</h1>
          </div>
          <div class="page-add__form">
            <form action="" method="post" id="js-travel-add-form" role="form" enctype="multipart/form-data">{% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-default">Опубликовать</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/travel/templates/travel/travel_list.html
{% extends 'base.html' %}
{% block content %}
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="travels">
          <div class="col-lg-12">
            <div class="page__title">
              <h1>{{ page.title|default:'Журнал путешествий' }}</h1>
            </div>
            {% if page.text %}
            <div class="page__text">
              <p>{{ page.text|safe|default:'' }}</p>
            </div>
            {% endif %}
          </div>
          {% for object in object_list %}
          <div class="col-lg-4 col-xs-12">
            <div class="travels-item">
              <div class="travels-item-cover">
                <img src="{{ object.cover_resize.url }}" class="travels-item-cover__img" alt="{{ object.title|default:'' }}">
              </div>
              <div class="travels-item-extra">
                <span class="travels-item-extra__date">{{ object.created }}</span>
                <span class="glyphicon glyphicon-eye-open"></span><span class="travels-item-extra__visit">{{ object.visit|default:'0' }}</span>
                <span class="glyphicon glyphicon-comment"></span><span class="travels-item-extra__comment">{{ object.comment|default:'0' }}</span>
                <a href="{{ object.get_absolute_url }}" class="travels-item__link">
                  <h2 class="travels-item__title">{{ object.title|default:'' }}</h2>
                  <p class="travels-item__text">
                    {{ object.text|striptags|truncatechars:100 }}
                  </p>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
          <div class="clearfix"></div>
        </div>
        {% include '__includes/pagination.html' %}
      </div>
    </div>
    <div class="authors">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h3 class="authors__title">Наши авторы</h3>
          </div>
          <div class="authors-list">
          {% for author in author_list %}
            {% if author.can_write_article and author.avatar != '' %}
            <div class="col-lg-6">
              <div class="authors-list-item">
                <div class="authors-list-item-avatar">
                  <img src="{{ author.avatar.url }}" alt="{{ author.get_full_name }}" class="authors-list-item-avatar__img">
                </div>
                <div class="authors-list-item-content">
                  <span class="authors-list-item-content__name">{{ author.get_full_name }}</span>
                  <span class="glyphicon glyphicon-edit"></span>
                  <span class="authors-list-item-content__article">({{ author.travel_set.all.count }})</span>
                  <p class="authors-list-item-content__text">
                    {{ author.desc|truncatechars:140|default:'Автор статей' }}
                  </p>
                  <a href="?author={{ author.id }}" class="authors-list-item-content__read btn btn-warning">Читать ></a>
                </div>
              </div>
            </div>
            {% endif %}
          {% endfor %}
            <div class="clearfix"></div>
          </div>
          <div class="authors-add">
          {% if user.is_authenticated %}
            {% if user.can_write_article %}
            <a href="{% url 'travels:add' %}" class="btn btn-success btn-lg">Добавить публикацию</a>
            {% else %}
            <p>Что бы начать писать статьи вам нужно полностью заполнить <a href="{% url 'profile' %}">профиль</a> - укажите свои имя, фамилию, придумайте оригинальную подпись и загрузите аватарку</p>
            {% endif %}
          {% else %}
            <p>Для того, что бы стать автором вам нужно <a href="#js-modal-auth" id="js-auth-button">ВОЙТИ</a> в свою учётную запись, либо
            <a href="#js-modal-auth" id="js-auth-button">ЗАРЕГИСТРИРОВАТЬСЯ</a></p>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}